<!--
document.write('<nav id="nav"> ');
document.write('  <div class="sm-nav-toggler"> ');
document.write('    <span class="lnr lnr-menu"></span> ');
document.write('    <span class="lnr lnr-cross"></span> ');
document.write('  </div> ');
document.write('  <ul class="main-menu"> ');
document.write('   <li> ');
document.write('     <a href="index.html"> ');
document.write('       <span class="lnr lnr-home"></span> ');
document.write('       <span class="nav-text">home</span> ');
document.write('     </a> ');
document.write('   </li> ');
document.write('   <li> ');
document.write('     <a class="scrolling" href="index.html#about"> ');
document.write('       <span class="lnr lnr-user"></span> ');
document.write('       <span class="nav-text">About</span> ');
document.write('     </a> ');
document.write('   </li> ');
document.write('   <li> ');
document.write('     <a href="resume.html"> ');
document.write('       <span class="lnr lnr-license"></span> ');
document.write('       <span class="nav-text">resume</span> ');
document.write('     </a> ');
document.write('   </li> ');
document.write('   <li> ');
document.write('     <a href="services.html"> ');
document.write('       <span class="lnr lnr-cog"></span> ');
document.write('       <span class="nav-text">services</span> ');
document.write('     </a> ');
document.write('   </li> ');
document.write('   <li> ');
document.write('     <a href="portfolio.html"> ');
document.write('       <span class="lnr lnr-briefcase"></span> ');
document.write('       <span class="nav-text">portfolio</span> ');
document.write('     </a> ');
document.write('   </li> ');
document.write('   <li> ');
document.write('     <a href="blog.html"> ');
document.write('       <span class="lnr lnr-leaf"></span> ');
document.write('       <span class="nav-text">blog</span> ');
document.write('     </a> ');
document.write('   </li> ');
document.write('   <li> ');
document.write('     <a href="contact.html"> ');
document.write('       <span class="lnr lnr-phone-handset"></span> ');
document.write('       <span class="nav-text">Contact</span> ');
document.write('     </a> ');
document.write('   </li> ');
document.write('  </ul> ');
document.write(' <div class="menu-bg"></div> ');
document.write('</nav> <!-- END nav--> ');
-->